import type { ResourceSpec } from '@/pages/shared/types';

export const transactions: ResourceSpec = {
  title: '账务流水',
  description: '按通话追踪扣费、余额变化和处理结果。',
  path: '/billing/transactions',
  idKey: 'id',
  readOnly: true,
  tableFieldLimit: 10,
  serverFilters: [
    { param: 'username', label: '账户', kind: 'select', optionsResource: 'accounts' },
    {
      param: 'entry_type',
      label: '流水类型',
      kind: 'select',
      options: [
        { label: '通话扣费', value: 'call_charge' },
        { label: '落地成本', value: 'call_cost' },
      ],
    },
    { param: 'call_id', label: '搜索', kind: 'keyword', placeholder: '按通话 ID 过滤...' },
    {
      param: 'time',
      label: '发生时间',
      kind: 'dateRange',
      startParam: 'start_time',
      endParam: 'end_time',
    },
  ],
  fields: [
    { key: 'created_at', label: '发生时间', kind: 'datetime' },
    { key: 'id', label: '流水号' },
    {
      key: 'entry_type',
      label: '流水类型',
      kind: 'select',
      options: [
        { label: '通话扣费', value: 'call_charge' },
        { label: '落地成本', value: 'call_cost' },
      ],
    },
    { key: 'call_id', label: '通话 ID' },
    { key: 'username', label: '账户' },
    { key: 'duration_ms', label: '计费时长（秒）', kind: 'duration' },
    { key: 'billing_interval_secs', label: '计费周期（秒）' },
    { key: 'price_per_interval', label: '周期价格（元）' },
    { key: 'amount', label: '金额（元）' },
    { key: 'balance_after', label: '余额（元）' },
  ],
};

export const calls: ResourceSpec = {
  title: '通话记录',
  description: '查询呼叫结果、时长、路由和媒体质量。',
  path: '/calls',
  idKey: 'call_id',
  detailPath: '/calls',
  readOnly: true,
  tableFieldLimit: 20,
  serverFilters: [
    {
      param: 'call_id',
      label: '搜索',
      kind: 'keyword',
      placeholder: '搜索通话 ID / 主叫 / 被叫...',
    },
    {
      param: 'status',
      label: '通话结果',
      kind: 'status',
      options: [
        { label: '全部', value: '' },
        { label: '已接通', value: 'answered' },
        { label: '未接通', value: 'failed' },
        { label: '已取消', value: 'canceled' },
        { label: '忙线', value: 'busy' },
        { label: '无应答', value: 'no_answer' },
      ],
    },
    {
      param: 'time',
      label: '呼叫时间',
      kind: 'dateRange',
      startParam: 'start_time',
      endParam: 'end_time',
    },
  ],
  fields: [
    { key: 'call_id', label: '通话 ID' },
    { key: 'caller', label: '主叫' },
    { key: 'callee', label: '被叫' },
    { key: 'status', label: '结果' },
    { key: 'failure_reason', label: '挂断原因 / SIP 状态' },
    { key: 'tenant_name', label: '租户' },
    { key: 'auth_realm', label: '鉴权域' },
    { key: 'started_at_ms', label: '开始时间', kind: 'datetime' },
    { key: 'duration_ms', label: '总时长', kind: 'duration' },
    { key: 'ringing_duration_ms', label: '振铃时长', kind: 'duration' },
    { key: 'billable_duration_ms', label: '通话时长', kind: 'duration' },
    { key: 'access_billable_duration_ms', label: '对接计费时长', kind: 'duration' },
    { key: 'access_charge_amount', label: '对接费用', kind: 'number' },
    { key: 'egress_billable_duration_ms', label: '落地计费时长', kind: 'duration' },
    { key: 'egress_cost_amount', label: '成本费用', kind: 'number' },
    { key: 'audit.ingress_trunk_id', label: '对接中继/网关' },
    { key: 'audit.billing_account', label: '对接账户' },
    { key: 'audit.egress_trunk_id', label: '落地中继/网关' },
    { key: 'audit.egress_billing_account', label: '落地账户' },
    {
      key: 'ringing_at_ms',
      label: '振铃时间',
      kind: 'datetime',
    },
    {
      key: 'answered_at_ms',
      label: '接通时间',
      kind: 'datetime',
    },
    {
      key: 'ended_at_ms',
      label: '结束时间',
      kind: 'datetime',
    },
  ],
};
